### ISSUE TITLE
KNX integration in error loop

### ISSUE THREAD

**Issue by krid002** [XKNX/knx-integration#15]
Hey,
I found my lights not turning on this morning.
-> entered HASS interface, which felt kind off inresponsive. tried to reset HASS thru interface without success
-> hard reset of promox VM with hass.

afterwards I took a look into the logs and I found this error message looping every .x seconds:

```
2024-12-08 09:19:19.620 ERROR (KNX Interface) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/xknx/io/tunnel.py", line 158, in _reconnect
    if await self.connect():
       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/xknx/io/tunnel.py", line 103, in connect
    self.xknx.connection_manager.connection_state_changed(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        XknxConnectionState.CONNECTING, self.connection_type
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/xknx/core/connection_manager.py", line 54, in connection_state_changed
    self._main_loop.call_soon_threadsafe(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._connection_state_changed, state, connection_type
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 874, in call_soon_threadsafe
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 552, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2024-12-08 09:19:19.620 ERROR (KNX Interface) [homeassistant] Error doing job: Task exception was never retrieved (None)
```

I am trying to find out when the first error appeared but apparently I can only view the logs in the webinterface and I do not find the entries in the /homeassistant/home-assistant.log or log.1 If you have an advice where to look for more logs or if you need more information kindly inform me.

**Comment by farmio** [comment]
Hi 👋! 
`RuntimeError: Event loop is closed` sounds to me like the symptom of a prior problem - as this should never happen as long as xknx is running.
Let me know if you can somehow reproduce this issue.

**Comment by krid002** [comment]
Hopefully it will not reproduce. 

I am still trying to find the first occurancy of this Error. But it seems I can only scroll the logs backwards in the web interface, as i did not find the correct files yet. And since the error occurs 10 times a second I doubt I will find the first one.

In any case thank you for your quick response.

**Comment by farmio** [comment]
You can find the full log file in your `config` directory: `home-assistant.log`

**Comment by krid002** [comment]
Yes I foudn that one but it's empty/showing only from the current start of the system. The .log.1 is also not showing the total output. How ever I scrolled thru log and found that the error above occured when the system was trying to shut down. Beforehand some more errors occured just some snipped right before the first occurancy of the loop:
```
024-12-08 09:18:11.631 WARNING (MainThread) [homeassistant.core] Timed out waiting for final writes to complete, the shutdown will continue
2024-12-08 09:18:11.631 WARNING (MainThread) [homeassistant.core] Shutdown stage 'final write': still running: <Task pending name='Task-3300823' coro=<KNXModule.stop() running at /usr/src/homeassistant/homeassistant/components/knx/__init__.py:311> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]>
2024-12-08 09:18:11.635 WARNING (MainThread) [homeassistant.core] Task <Task pending name='Task-271166' coro=<async_enable_report_state.<locals>.report_states() running at /usr/src/homeassistant/homeassistant/components/google_assistant/report_state.py:58> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]> cb=[set.remove()]> was still running after final writes shutdown stage; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown
2024-12-08 09:18:21.930 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/kodi/media_player.py", line 452, in _async_connect_websocket_if_disconnected
    await self._async_ws_connect()
  File "/usr/src/homeassistant/homeassistant/components/kodi/media_player.py", line 428, in _async_ws_connect
    await self._connection.connect()
  File "/usr/local/lib/python3.13/site-packages/pykodi/kodi.py", line 135, in connect
    await self._ws_server.ws_connect()
  File "/usr/local/lib/python3.13/site-packages/jsonrpc_websocket/jsonrpc.py", line 65, in ws_connect
    self._client = await self._session.ws_connect(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._url, **self._connect_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 1002, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 512, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
2024-12-08 09:18:31.803 ERROR (KNX Interface) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/kodi/media_player.py", line 452, in _async_connect_websocket_if_disconnected
    await self._async_ws_connect()
  File "/usr/src/homeassistant/homeassistant/components/kodi/media_player.py", line 428, in _async_ws_connect
    await self._connection.connect()
  File "/usr/local/lib/python3.13/site-packages/pykodi/kodi.py", line 135, in connect
    await self._ws_server.ws_connect()
  File "/usr/local/lib/python3.13/site-packages/jsonrpc_websocket/jsonrpc.py", line 65, in ws_connect
    self._client = await self._session.ws_connect(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._url, **self._connect_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 1002, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 512, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
2024-12-08 09:18:41.609 ERROR (KNX Interface) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/kodi/media_player.py", line 452, in _async_connect_websocket_if_disconnected
    await self._async_ws_connect()
  File "/usr/src/homeassistant/homeassistant/components/kodi/media_player.py", line 428, in _async_ws_connect
    await self._connection.connect()
  File "/usr/local/lib/python3.13/site-packages/pykodi/kodi.py", line 135, in connect
    await self._ws_server.ws_connect()
  File "/usr/local/lib/python3.13/site-packages/jsonrpc_websocket/jsonrpc.py", line 65, in ws_connect
    self._client = await self._session.ws_connect(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._url, **self._connect_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 1002, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 512, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
2024-12-08 09:18:41.638 WARNING (MainThread) [homeassistant.core] Timed out waiting for close event to be processed, the shutdown will continue
2024-12-08 09:18:41.638 WARNING (MainThread) [homeassistant.core] Shutdown stage 'close': still running: <Task pending name='Task-3300823' coro=<KNXModule.stop() running at /usr/src/homeassistant/homeassistant/components/knx/__init__.py:311> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]>
2024-12-08 09:19:01.503 ERROR (KNX Interface) [homeassistant] Error doing job: Task exception was never retrieved (None)
```
and then the error loop began.

how ever I'd say we close this issue since the system was not really stable before.

Scrolling further thru the error log i get these msgs:


```
2024-12-08 09:13:02.213 WARNING (KNX Interface) [xknx.log] No active communication channel.
2024-12-08 09:13:02.213 WARNING (KNX Interface) [xknx.log] No active communication channel.
2024-12-08 09:13:02.213 WARNING (KNX Interface) [xknx.log] No active communication channel. 
```

sometimes interrupted by msg like:
```
2024-12-08 09:07:38.287 WARNING (KNX Interface) [xknx.log] No active communication channel.
2024-12-08 09:07:40.077 WARNING (MainThread) [xknx.cemi] Could not send CEMI frame: Sending telegram failed. No active communication channel. for <CEMIFrame code="L_DATA_REQ" info="CEMIInfo("")" data="CEMILData(src_addr="IndividualAddress("1.1.145")" dst_addr="GroupAddress("6/7/1")" flags="1011110011100000" tpci="TDataGroup()" payload="<GroupValueWrite value="<DPTBinary value="0" />" />")" />
2024-12-08 09:07:40.077 WARNING (MainThread) [xknx.log] Sending telegram failed. No active communication channel.
```

still scrolling for the first occurancy of this error but it seems to be a new issue if I find it.
